delete from CONFIGURATION_PROPERTIES;
delete from CONFIGURATION_PROPERTY;
delete from CONFIGURATION;


select * from CONFIGURATION;
select * from CONFIGURATION_PROPERTY;
select * from CONFIGURATION_PROPERTIES;