# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: 
    - develop
    - master
    - 'releases/**'
  pull_request:
    branches:
    - develop
    - master
    - 'releases/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: oss.sonatype.org             # distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }}  # location for the settings.xml file
        server-username: ${{ secrets.OSS_SONATYPE_USERNAME }}
        server-password: ${{ secrets.OSS_SONATYPE_PASSWORD }}
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        gpg-passphrase:  ${{ secrets.MAVEN_GPG_PASSPHRASE }}

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to Apache Maven Central
      run: mvn -B deploy -Pkaleido-central-deploy -s $GITHUB_WORKSPACE/settings.xml

